name: in_porto
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  animations: ^2.0.11
  google_maps_flutter: ^2.12.3
  google_fonts: ^8.0.0
  shared_preferences: ^2.5.3
  provider: ^6.1.5
  intl: ^0.20.2
  flutter_localizations:
    sdk: flutter
  http: ^1.4.0
  archive: ^4.0.7
  csv: ^6.0.0
  objectbox: ^5.2.0
  objectbox_flutter_libs: ^5.2.0
  path_provider: ^2.1.5
  connectivity_plus: ^7.0.0
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  change_app_package_name: ^1.5.0
  build_runner: ^2.10.5
  objectbox_generator: ^5.2.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
