name: in_porto
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  animations: ^2.0.11
  google_maps_flutter: ^2.12.3
  google_fonts: ^8.0.0
  shared_preferences: ^2.5.3
  provider: ^6.1.5
  intl: ^0.20.2
  flutter_localizations:
    sdk: flutter
  http: ^1.4.0
  connectivity_plus: ^7.0.0
  flutter_riverpod: ^3.1.0
  riverpod_generator: ^4.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  change_app_package_name: ^1.5.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
